version: '3'
services:
  game-mysql:
    container_name: game-mysql        # 指定容器的名称
    image: mysql:5.7                   # 指定镜像和版本
    restart: always
    networks:
      - outside
    ports:
      - "3308:3306" #端口映射
    environment:
      MYSQL_DATABASE: mysql            #数据库名
      MYSQL_ROOT_PASSWORD: "game2022" #数据库密码
      MYSQL_USER: 'test'
      MYSQL_PASS: 'test'
      MYSQL_ROOT_HOST: '%'               #开放所有ip访问
    volumes:
      - ./data:/var/lib/mysql          # 挂载数据目录
      - ./my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf #cnf 默认文件配置
      - ./init:/docker-entrypoint-initdb.d/  #初始化sql脚本配置
      - ./log:/var/log/mysql
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
networks:
  outside:
    external:
      name: game
